[package]
name = "vrc-get-gui"
version = "0.1.0-beta.15"
description = "A Tauri App"

homepage.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[build-dependencies]
flate2 = "1.0.28"
tar = "0.4.40"
tauri-build = { version = "1.5.1", features = [ "config-toml" ] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.1", features = [ "updater", "shell-open", "config-toml", "dialog" ] }
vrc-get-vpm = { path = "../vrc-get-vpm", features = ["experimental-project-management", "experimental-unity-management", "tokio"] }
reqwest = "0.12.1"
specta = { version = "1.0.5", features = [ "chrono" ] }
tauri-specta = { version = "1.0.2", features = ["typescript"] }
open = "5.1.2"
arc-swap = "1.7.0"
log = { version = "0.4.21", features = [ "std" ] }
chrono = { version = "0.4.35", features = [ "serde" ] }
ringbuffer = "0.15.0"
tokio = { version = "1.36.0", features = ["process"] }
fs_extra = "1.3.0"
indexmap = "2.2.5"
futures = "0.3.30"
tar = "0.4.40"
flate2 = "1.0.28"
uuid = { version = "1.7.0", features = ["v4"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
